data_sources:
  main:
    url: <%= ENV["BLAZER_DATABASE_URL"] %>
    timeout: 15
    # use_transaction: true
    # cache: 60
    linked_columns:
      title: "http://us.imdb.com/M/title-exact?{value}"
      zip_code: "https://www.google.com/search?q={value}"
    smart_columns:
      occupation_id: "SELECT id, name FROM occupations WHERE id IN {value}"
      movie_id: "SELECT id, title FROM movies WHERE id IN {value}"
      genre_id: "SELECT id, name FROM genres WHERE id IN {value}"
    smart_variables:
      movie_id: "SELECT id, title FROM movies ORDER BY title ASC"
      occupation_id: "SELECT id, name FROM occupations ORDER BY name ASC"
      genre_id: "SELECT id, name FROM genres ORDER BY name ASC"
  non_standard_schema: 
    url: <%= ENV["BLAZER_DATABASE_URL"] %>
    schemas: ['secondary']
  # catalog:
  #   url: <%= ENV["BLAZER_CATALOG_DATABASE_URL"] %>

time_zone: "Eastern Time (US & Canada)"

audit: true

anomaly_checks: true

images: true

check_schedules:
  - "5 minutes"
  - "1 hour"
  - "1 day"
  - "1 week"
